/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active ads for display (keyset pagination by id) */
        get: operations["listActiveAds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ads/{ad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One active ad */
        get: operations["getAd"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up a new advertiser (any valid token) */
        post: operations["createAdvertiser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers/{advertiser_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdvertiser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers/{advertiser_id}/ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All ads of the advertiser (active and inactive), ordered by id */
        get: operations["listAdvertiserAds"];
        put?: never;
        post: operations["createAd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers/{advertiser_id}/ads/{ad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the editable fields of an ad (also re-activates with active=true) */
        put: operations["updateAd"];
        post?: never;
        /** Soft delete (active = false). Idempotent. */
        delete: operations["deactivateAd"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: string;
        };
        AdvertiserCreate: {
            name: string;
        };
        Advertiser: {
            id: number;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        AdCreate: {
            content: string;
            /** Format: uri */
            img_url?: string | null;
            /**
             * Format: uri
             * @description absolute http(s) URL
             */
            redirect_url: string;
        };
        AdUpdate: {
            content: string;
            /** Format: uri */
            img_url?: string | null;
            /** Format: uri */
            redirect_url: string;
            active: boolean;
        };
        Ad: {
            id: number;
            advertiser_id: number;
            content: string;
            img_url: string | null;
            redirect_url: string;
            active: boolean;
            /** @description Relative click link without the user: `/api/click-receiver/click/{id}`. Clients append `?user_id=<id>`. */
            click_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdPage: {
            items: components["schemas"]["Ad"][];
            /** @description null when this is the last page */
            next_after_id: number | null;
        };
    };
    responses: {
        /** @description No verified identity (normally answered by the gateway) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not the owner / wrong role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such advertiser/ad (or ad not owned by this advertiser, or inactive for /ads/{ad_id}) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AdvertiserId: number;
        AdId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listActiveAds: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return ads with id > after_id (use `next_after_id` from the previous page) */
                after_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of active ads, ordered by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ad_id: components["parameters"]["AdId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ad */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAdvertiser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvertiserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advertiser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdvertiser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The advertiser */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advertiser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdvertiserAds: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Ad"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createAd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
                ad_id: components["parameters"]["AdId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deactivateAd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
                ad_id: components["parameters"]["AdId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
