/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/advertisers/{advertiser_id}/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clicks over time for all ads of the advertiser, plus per-ad totals */
        get: operations["getAdvertiserClicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advertisers/{advertiser_id}/ads/{ad_id}/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clicks over time for one ad of the advertiser
         * @description An ad with no rows (or one of another advertiser) returns a zero-filled series, not 404 — analytics does not know the ads catalogue.
         */
        get: operations["getAdClicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: string;
        };
        Point: {
            /**
             * Format: date-time
             * @description Bucket start (UTC)
             */
            start: string;
            clicks: number;
        };
        Freshness: {
            /**
             * Format: date-time
             * @description max(updated_at) of the rows in range; null when there are none
             */
            last_updated_at: string | null;
        };
        AdTotal: {
            ad_id: number;
            clicks: number;
        };
        AdClicks: {
            advertiser_id: number;
            ad_id: number;
            /** @enum {string} */
            granularity: "minute" | "hour" | "day";
            /**
             * Format: date-time
             * @description Effective (truncated) start
             */
            from: string;
            /**
             * Format: date-time
             * @description Effective (rounded up) exclusive end
             */
            to: string;
            total: number;
            points: components["schemas"]["Point"][];
            freshness: components["schemas"]["Freshness"];
        };
        AdvertiserClicks: {
            advertiser_id: number;
            /** @enum {string} */
            granularity: "minute" | "hour" | "day";
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            total: number;
            points: components["schemas"]["Point"][];
            /** @description Per-ad totals over the range, clicks descending, only ads with clicks > 0 */
            by_ad: components["schemas"]["AdTotal"][];
            freshness: components["schemas"]["Freshness"];
        };
    };
    responses: {
        /** @description from >= to, or more than 1440 buckets */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No verified identity (normally answered by the gateway) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not this advertiser / not an advertiser token */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AdvertiserId: number;
        /** @description RFC 3339 timestamp (default to - 1h) */
        From: string;
        /** @description RFC 3339 timestamp, exclusive (default now) */
        To: string;
        Granularity: "minute" | "hour" | "day";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAdvertiserClicks: {
        parameters: {
            query?: {
                /** @description RFC 3339 timestamp (default to - 1h) */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp, exclusive (default now) */
                to?: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvertiserClicks"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdClicks: {
        parameters: {
            query?: {
                /** @description RFC 3339 timestamp (default to - 1h) */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp, exclusive (default now) */
                to?: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                advertiser_id: components["parameters"]["AdvertiserId"];
                ad_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdClicks"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
