/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a 1 h token for a viewer (end user) or an advertiser
         * @description Claims: `sub` (viewer: the user_id; advertiser: `advertiser:<id>`), `role`,
         *     `advertiser_id` (decimal string; `""` for viewers), `iss`, `aud`, `iat`, `exp`; header `kid`.
         *     Does not check that the advertiser exists (demo login).
         */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public key set for verifying tokens */
        get: operations["getJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenRequest: {
            /** @enum {string} */
            role: "viewer" | "advertiser";
            /** @description Required when role = viewer */
            user_id?: string;
            /** @description Required when role = advertiser */
            advertiser_id?: number;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Seconds (3600) */
            expires_in: number;
            /** @enum {string} */
            role: "viewer" | "advertiser";
            advertiser_id?: number | null;
            user_id?: string | null;
        };
        Jwks: {
            keys: {
                /** @enum {string} */
                kty: "RSA";
                kid: string;
                /** @enum {string} */
                use: "sig";
                /** @enum {string} */
                alg: "RS256";
                n: string;
                e: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Signed token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid request (e.g. role=advertiser without advertiser_id, role=viewer without user_id) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JWKS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jwks"];
                };
            };
        };
    };
}
