/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/click/{ad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Record a click and redirect the browser to the ad's redirect_url */
        get: operations["clickRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a click and return the redirect target as JSON (for SPAs and tests) */
        post: operations["recordClick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hot-ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This receiver's current view of hot ads (refreshed from Redis every ~2 s) */
        get: operations["listHotAds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: string;
        };
        ClickRequest: {
            ad_id: number;
            user_id: string;
        };
        ClickResult: {
            /** Format: uuid */
            click_id: string;
            /** @enum {string} */
            status: "accepted" | "duplicate";
            ad_id: number;
            redirect_url: string;
            /** Format: date-time */
            clicked_at: string;
            /** @description Same as X-Click-Hot */
            hot: boolean;
        };
        HotAd: {
            ad_id: number;
            /** @description marks >= HOT_PERMANENT_AFTER_MARKS */
            permanent: boolean;
            /** @description Times the ad has been marked hot */
            marks: number;
            /**
             * Format: date-time
             * @description When the temporary marking expires unless renewed; null for permanent ads without a current marking
             */
            hot_until: string | null;
        };
        HotAds: {
            /**
             * Format: date-time
             * @description Last successful refresh from Redis
             */
            refreshed_at: string | null;
            threshold_clicks_10m: number;
            salt_buckets: number;
            salting_enabled: boolean;
            items: components["schemas"]["HotAd"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clickRedirect: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path: {
                ad_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted or duplicate; redirect to the advertiser */
            302: {
                headers: {
                    /** @description The ad's redirect_url */
                    Location: string;
                    "X-Click-Status": "accepted" | "duplicate";
                    "X-Click-Id": string;
                    "X-Click-Hot": "true" | "false";
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or inactive ad; nothing recorded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing/invalid user_id or ad_id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Click could not be durably recorded (Kafka ack failed/timed out); no redirect, the client may retry */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    recordClick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClickRequest"];
            };
        };
        responses: {
            /** @description Accepted or duplicate */
            200: {
                headers: {
                    "X-Click-Status": "accepted" | "duplicate";
                    "X-Click-Id": string;
                    "X-Click-Hot": "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClickResult"];
                };
            };
            /** @description Unknown or inactive ad; nothing recorded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Click could not be durably recorded; the client may retry */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listHotAds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hot ads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotAds"];
                };
            };
        };
    };
}
