apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 24h
  url: https://strimzi.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kafbat
  namespace: flux-system
spec:
  interval: 24h
  url: https://ui.charts.kafbat.io/
