apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 10m
  releaseName: cnpg
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.29.0          # operator 1.30.0
      sourceRef: { kind: HelmRepository, name: cnpg }
  install: { createNamespace: true, crds: CreateReplace, remediation: { retries: 3 } }
  upgrade: { crds: CreateReplace, remediation: { retries: 3 } }
